dwa_planner:
  ros__parameters:
    goal_x: 1.5
    goal_y: 0.0
    max_vel_x: 0.22        # TB3 burger default
    min_vel_x: 0.0
    max_vel_theta: 2.84    # TB3 burger default
    acc_lim_x: 0.25
    acc_lim_theta: 3.2
    sim_time: 1.0
    sim_dt: 0.1
    v_samples: 10
    omega_samples: 20
    robot_radius: 0.12
    safety_margin: 0.03
    heading_weight: 2.5
    clearance_weight: 1.5
    velocity_weight: 0.8
    smoothness_weight: 0.5
    control_rate_hz: 10.0
